### ISSUE TITLE
Question: Partial downloads to an xml decoder?

### ISSUE THREAD

**Issue by wari** [klauspost/readahead#4]
I wonder, would this be useful for a case like:

Input: Partial downloads of say 16K chunks every iteration
ReadAhead: Buffers, say 32K chunks (or any configurable size)
xml.Decoder: Consumes the buffers to populate a struct.

Thanks.

**Comment by klauspost** [comment]
I am pretty sure it will not _hurt_ your performance. 

It really depends on your download speed. Unless you have a very high download speed or the XML decoder is slow, it will probably not make a huge difference, since it will spend 95% of its time waiting for data from the download to become available anyway. But the last 5% is probably worth taking anyway.

**Comment by wari** [comment]
Thanks. Speed is not a concern, the requirement is the ability to download the data in separate chunks and passing the bits to the decoder a bit at a time instead of downloading it fully.

As you know, the decoder will stop immediately when it hits an EOF, I just need to create a reader that will download the next bits and pass it to readahead.
